name: primer_prototipo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  geolocator: ^14.0.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - android/assets/images/

# -------- Icono de la app --------
flutter_launcher_icons:
  android: true
  ios: true

  # Debes tener este archivo en android/assets/images/
  image_path_android: android/assets/images/LOGO_HOJA_ID_.png   # Android
  image_path_ios:     android/assets/images/LOGO_HOJA_ID_.png  # iOS

  # Adem치s para Android 8+ (adaptive icon)
  adaptive_icon_foreground: android/assets/images/LOGO_HOJA_ID_.png
  adaptive_icon_background: "#E8F5E9"
  min_sdk_android: 21

# ------- Splash nativo (Android/iOS) -------
flutter_native_splash:
  android: true
  ios: true

  # Fondo (puedes cambiarlo)
  color: "#0E0F10"
  color_dark: "#0E0F10"

  # Logo (debe estar en assets con transparencia)
  image: android/assets/images/LOGO_HOJA_ID_.png
  image_dark: android/assets/images/LOGO_HOJA_ID_.png

  # Configuraci칩n para Android 12+
  android_12:
    color: "#0E0F10"
    color_dark: "#0E0F10"
    image: android/assets/images/LOGO_HOJA_ID_.png
    image_dark: android/assets/images/LOGO_HOJA_ID_.png

  # 游녢 Ajustes de tama침o/posici칩n
  android_gravity: center       # Centrado en Android
  ios_content_mode: scaleAspectFit # Ajustado proporcional en iOS
